### ISSUE TITLE
TypeError: a bytes-like object is required, not 'str'

### ISSUE THREAD

**Issue by Pooran-Dewari** [hoffmangroup/umap#10]
Hello,
I have been trying to set up umap but the test run gives me this error:
File "get_kmers.py", line 201, in get_seq_ar
    if "chr" in seq_ar[0]:
TypeError: a bytes-like object is required, not 'str'

Command: Just using the recommended commands for the test data run in my conda env with python 2.7
`python ubismap.py data/genome.fa data/chrsize.tsv data/TestGenomeMappability all.q $BOWTIEDIR/bowtie-build --kmer 8 12 -write_script test_run.sh`
`sh test_run.sh`

Please suggest how to get around this error. @mehrankr @EricR86
Thanks for your help.

**Comment by mehrankr** [comment]
Hello Pooran,

I know you are using python 2.7, but can you provide the exact version?

This seems to be an issue with encode/decode when reading the files. So if you modify the script to decode after reading, by adding the ".decode()" it should work fine.

**Comment by mehrankr** [comment]
I justed tested the latest version with `Python 2.7.18` and test data and it works just fine

**Comment by Pooran-Dewari** [comment]
Hi Mehran,
Thanks for your reply. I had last run with python 2.7.15; I am testing now with 2.7.18, fingers-crossed!!
I did try decode('utf-8') with my previous runs, but then it started throwing some other errors (sorry don't have log for that, but it was along the lines 'not byte memory'). 
Did you mean include the decode() implementation with 2.7.18 to make it work? 
thanks

**Comment by mehrankr** [comment]
It should work with 2.7.18 without any modifications. Send me the log if it doesn't work.
Here are the commands I tried:
```
python ubismap.py data/genome.fa data/chrsize.tsv data/TestGenomeMappability all.q $BOWTIEDIR/bowtie-build --kmer 8 12 -write_script test_run.sh

export SGE_TASK_ID=1; python get_kmers.py data/TestGenomeMappability/chrsize.tsv data/TestGenomeMappability/kmers/k8 data/TestGenomeMappability/chrs data/TestGenomeMappability/chrsize_index.tsv --var_id SGE_TASK_ID --kmer k8


python run_bowtie.py data/TestGenomeMappability/kmers/k8 /Users/mehran/anaconda3/envs/py27/bin data/TestGenomeMappability/genome Umap_bowtie.ind -var_id SGE_TASK_ID


```

**Comment by Pooran-Dewari** [comment]
Hi Mehran,

Test run with python 2.7.18 & numpy-1.16.6 pandas-0.24.2 python-dateutil-2.8.2 pytz-2022.6 six-1.16.0 gives me the following error:
`$ cat Bismap.UniqueKmers.ERR
Traceback (most recent call last):
  File "get_kmers.py", line 127, in get_region
    each_line in ["Chromosome", "Start", "End"]]
  File "get_kmers.py", line 127, in <listcomp>
    each_line in ["Chromosome", "Start", "End"]]
KeyError: 2

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "get_kmers.py", line 266, in <module>
    idx_path)
  File "get_kmers.py", line 98, in __init__
    self.chrom, self.start, self.end = self.get_region()
  File "get_kmers.py", line 131, in get_region
    job_id))
ValueError: 2 Job id is larger than available indices
Traceback (most recent call last):
  File "get_kmers.py", line 267, in <module>
    GetKmerObj.write_region()
  File "get_kmers.py", line 251, in write_region
    seq_ar = self.get_seq_ar(fasta_fix)
  File "get_kmers.py", line 201, in get_seq_ar
    if "chr" in seq_ar[0]:
TypeError: a bytes-like object is required, not 'str'
Traceback (most recent call last):
  File "get_kmers.py", line 267, in <module>
    GetKmerObj.write_region()
  File "get_kmers.py", line 251, in write_region
    seq_ar = self.get_seq_ar(fasta_fix)
  File "get_kmers.py", line 201, in get_seq_ar
    if "chr" in seq_ar[0]:
TypeError: a bytes-like object is required, not 'str'
Traceback (most recent call last):
  File "get_kmers.py", line 127, in get_region
    each_line in ["Chromosome", "Start", "End"]]
  File "get_kmers.py", line 127, in <listcomp>
    each_line in ["Chromosome", "Start", "End"]]
KeyError: 2

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "get_kmers.py", line 266, in <module>
    idx_path)
  File "get_kmers.py", line 98, in __init__
    self.chrom, self.start, self.end = self.get_region()
  File "get_kmers.py", line 131, in get_region
    job_id))
ValueError: 2 Job id is larger than available indices
Traceback (most recent call last):
  File "get_kmers.py", line 267, in <module>
    GetKmerObj.write_region()
  File "get_kmers.py", line 251, in write_region
    seq_ar = self.get_seq_ar(fasta_fix)
  File "get_kmers.py", line 201, in get_seq_ar
    if "chr" in seq_ar[0]:
TypeError: a bytes-like object is required, not 'str'
Traceback (most recent call last):
  File "get_kmers.py", line 267, in <module>
    GetKmerObj.write_region()
  File "get_kmers.py", line 251, in write_region
    seq_ar = self.get_seq_ar(fasta_fix)
  File "get_kmers.py", line 201, in get_seq_ar
    if "chr" in seq_ar[0]:
TypeError: a bytes-like object is required, not 'str'`

I have used bowtie1.1.2
`python ubismap.py data/genome.fa data/chrsize.tsv data/TestGenomeMappability all.q /exports/igmm/software/pkg/el7/apps/bowtie/1.1.2/bowtie-build --kmer 8 12 -write_script test_run.sh`

thanks

**Comment by mehrankr** [comment]
Can you just run the following commands to make sure the programs runs on a single job id correctly?

```
python ubismap.py data/genome.fa data/chrsize.tsv data/TestGenomeMappability all.q $BOWTIEDIR/bowtie-build --kmer 8 12 -write_script test_run.sh

export SGE_TASK_ID=1

python get_kmers.py data/TestGenomeMappability/chrsize.tsv data/TestGenomeMappability/kmers/k8 data/TestGenomeMappability/chrs data/TestGenomeMappability/chrsize_index.tsv --var_id SGE_TASK_ID --kmer k8


python run_bowtie.py data/TestGenomeMappability/kmers/k8 /Users/mehran/anaconda3/envs/py27/bin data/TestGenomeMappability/genome Umap_bowtie.ind -var_id SGE_TASK_ID
```

`export SGE_TASK_ID=1` on line 2 makes sure the program runs on only one job id. If that doesn't throw any error, everything is fine.

**Comment by mehrankr** [comment]
Type `which bowtie` and it will return something like `/Users/mehran/anaconda3/envs/py27/bin/bowtie` and use the part that doesn't include `/bowtie` in the end (the folder containing bowtie and bowtie-build executables)

**Comment by Pooran-Dewari** [comment]
alright, looks like it worked :)

$ `python run_bowtie.py data/TestGenomeMappability/kmers/k8 /exports/igmm/software/pkg/el7/apps/bowtie/1.1.2/ data/TestGenomeMappability/genome Umap_bowtie.ind -var_id SGE_TASK_ID`
processing Kmer File data/TestGenomeMappability/kmers/k8/chr1.0.8.kmer.gz
# reads processed: 24
# reads with at least one reported alignment: 9 (37.50%)
# reads that failed to align: 0 (0.00%)
# reads with alignments suppressed due to -m: 15 (62.50%)
Reported 9 alignments to 1 output stream(s)
Executing gunzip -c data/TestGenomeMappability/kmers/k8/chr1.0.8.kmer.gz | /exports/igmm/software/pkg/el7/apps/bowtie/1.1.2//bowtie data/TestGenomeMappability/genome/Umap_bowtie.ind -v 0 -k 1 -m 1 --mm -r --refidx --suppress 5,6,7,8 - | gzip -c > data/TestGenomeMappability/kmers/k8/chr1.0.8.bowtie.gz

Only thing I don't understand is why it gives me error when I ran it without the export SGE_TASK_ID=1. I am really desperate to make it work as the whole pipeline we are developing for our consortium lab partners is bottlenecked with this blacklist file step & do appreciated your help.

**Comment by mehrankr** [comment]
I'm glad it worked.

Please take a look at the documentation, particularly the part explaining how to run this with slurm job scheduler. That should help you with understanding how this works.

What I can say and maybe you know already is that the program works on slices of the genome (typically hundreds), and it finds those slices based on an environmental variable which in this case is set to SGE_TASK_ID.

SGE and Slurm have different environmental variables so you need to define -var_id to be compatible with that.

If you don't have access to SGE or Slurm, you can still use it in a for loop by utilizing -job_id instead and passing indices directly to job_id.

Example:
```
for i in {0..10}:
do
    python get_kmers.py data/TestGenomeMappability/chrsize.tsv data/TestGenomeMappability/kmers/k8 data/TestGenomeMappability/chrs data/TestGenomeMappability/chrsize_index.tsv -job_id $i --kmer k8
done
```

Good luck,
Mehran

**Comment by Pooran-Dewari** [comment]
Thanks for your help, much appreciated.

**Comment by Pooran-Dewari** [comment]
Apologies, Last question:
I can run these successfully via commands above, but it creates kmers for only one chromosome, also can see it does for only few entries of the chrsize_index, not the whole chromosome.

`python get_kmers.py data/TestGenomeMappability/chrsize.tsv data/TestGenomeMappability/kmers/k150 data/TestGenomeMappability/chrs data/TestGenomeMappability/chrsize_index.tsv -job_id $i --kmer k150`

`k150]$ ls`
chr3.0.150.kmer.gz  TEMPs


$ cat data/genome.fa | grep 'chr' -A 2 
>chr3
TTTATGACacccattcagagttaatgactcgcccattcagagttaatgactcgcccattc
agagttaatgactcgcccattcagagttaatgactcaccgattcagagttaatgactcac
--
>chr6
TACTCTCTGGCTCTCGTTTCCTGTGAGTTCTAAATGCAGGCAGAGGAAATACCACTGTGT
GTGTGGGTCATTGTTAAGCGTCCTGTCTTTGTCCAAACATTTCTCTCATTAACATTACGA

$ cat data/chrsize.tsv 
chr3	105780080
chr6	96060288

Would it be too much bother if I sent you chrsize file and link to genome assembly, and you could run it for us. Thanks

**Comment by mehrankr** [comment]
1. Can you post the full history of the commands you are using?

2. Do you have access to a server with slurm or SGE?

From the output of `ls` it seems only the first job is running.

**Comment by Pooran-Dewari** [comment]
I re-ran the code below via bash
```
for i in {0..204..1};
do
    python get_kmers.py data/TestGenomeMappability/chrsize.tsv data/TestGenomeMappability/kmers/k150 data/TestGenomeMappability/chrs data/TestGenomeMappability/chrsize_index.tsv -job_id $i --kmer k150
    #echo "$i"
done
```
Can see that it processes 1000000 bases per $i in -job_id.

**Comment by mehrankr** [comment]
That's strange.

Sure, email me the links, I will take a look.
It might take at least a few weeks since it's been years I'm not in Hoffman lab and have to do this on my own free time.

**Comment by Pooran-Dewari** [comment]
Thanks. I am gonna give it a last try before I give in.
Using the for loop as above, I managed to run bowtie for both chromosomes. It has generated ~100 bowties files per $i for each chr.
Below is `head` for one such file (hope it looks as expected?)
```
$ zcat data/TestGenomeMappability/kmers/k150/chr3.10.150.bowtie.gz | head
0	+	0	9999791
1	+	0	9999792
2	+	0	9999793
3	+	0	9999794
4	+	0	9999795
5	+	0	9999796
6	+	0	9999797
7	+	0	9999798
8	+	0	9999799
9	+	0	9999800
```

Just need to run the last step `unify` now, I used the commands below to unify.

```
$ export SGE_TASK_ID=1
$ module load igmm/apps/bowtie/1.1.2
$ python unify_bowtie.py data/TestGenomeMappability/kmers/k150 data/TestGenomeMappability/chrsize.tsv -var_id SGE_TASK_ID
Done with data/TestGenomeMappability/kmers/k150/chr3.102.150.bowtie.gz
Done with data/TestGenomeMappability/kmers/k150/chr3.66.150.bowtie.gz
Done with data/TestGenomeMappability/kmers/k150/chr3.59.150.bowtie.gz 
..
..
..
Done with data/TestGenomeMappability/kmers/k150/chr3.96.150.bowtie.gz
Done with data/TestGenomeMappability/kmers/k150/chr3.54.150.bowtie.gz
For data/TestGenomeMappability/kmers/k150/chr3.k150.uint8.unique.gz found 92901015 unique regions
Saved data/TestGenomeMappability/kmers/k150/chr3.k150.uint8.unique.gz
Exiting successfully
```
But when I try to `zcat data/TestGenomeMappability/kmers/k150/chr3.k150.uint8.unique.gz` , it doesn't output anything.. probably empty? size of the file is 384k, which is much smaller than individual bowtie.gz files which are in MB.

thanks

**Comment by mehrankr** [comment]
To investigate the content of chr3.k150.uint8.unique.gz files, please use this in python:

```
uint_path = "chr3.k150.uint8.unique.gz"
kmer_link = gzip.open(uint_path, "rb")
kmer_ar = np.frombuffer(kmer_link.read(), dtype=np.uint8)
kmer_link.close()
```

See how https://github.com/hoffmangroup/umap/blob/master/umap/combine_umaps.py manages these files.

**Comment by Pooran-Dewari** [comment]
Thanks. I can't see any output after running the python script from above, no error message either.

**Comment by Pooran-Dewari** [comment]
Probably missing some arguments here that messes up final output?
`export SGE_TASK_ID=1`
`python unify_bowtie.py data/TestGenomeMappability/kmers/k150 data/TestGenomeMappability/chrsize.tsv -var_id SGE_TASK_ID`

**Comment by mehrankr** [comment]
The python script shows how to load the content into kmer_ar object in python.
then you can examine it with basic python and numpy commands if you want.

Example:
```
uint_path = "chr3.k150.uint8.unique.gz"
kmer_link = gzip.open(uint_path, "rb")
kmer_ar = np.frombuffer(kmer_link.read(), dtype=np.uint8)
kmer_link.close()
idx_nonzeros = np.where(kmer_ar > 0)[0]
print("This array has {} non-zero k-mers".format(len(idx_nonzeros)))
```

unify_bowtie expects a job id corresponding to the chromosome (it merges all the bowtie files corresponding to each single chromosome. So if you have 23 chromosomes, it will be:

```
for i in {1..23}
do
    python unify_bowtie.py data/TestGenomeMappability/kmers/k150 data/TestGenomeMappability/chrsize.tsv -job_id $i
done
```

**Comment by Pooran-Dewari** [comment]
Thanks. I was testing with chr3 and chr6 for fish genome, `for i in 3 6;` gives me error but I will try with all 29 chromosomes and see how it goes.

**Comment by Pooran-Dewari** [comment]
Testing with test data for 8 kmer for chr1 and chr2.

k8/ has all the kmer and bowtie gzip files.
```
 k8
    ├── chr1.0.8.bowtie.gz
    ├── chr1.0.8.kmer.gz
    ├── chr2.1.8.bowtie.gz
    ├── chr2.1.8.kmer.gz
    └── TEMPs
```

I have this code inside my jobs.sh bash script.

```
for i in {1..2}
do
    python unify_bowtie.py data/TestGenomeMappability/kmers/k8 data/TestGenomeMappability/chrsize.tsv -job_id $i
    echo "done for the $i"
done
```

Running jobs.sh gives me this error:

```
$ . jobs.sh 
Done with data/TestGenomeMappability/kmers/k8/chr2.1.8.bowtie.gz
For data/TestGenomeMappability/kmers/k8/chr2.k8.uint8.unique.gz found 5 unique regions
Saved data/TestGenomeMappability/kmers/k8/chr2.k8.uint8.unique.gz
Exiting successfully
done for the 1
Traceback (most recent call last):
  File "unify_bowtie.py", line 169, in <module>
    UnifyBowtie(args.bowtie_outdir, args.chrsize_path, job_id)
  File "unify_bowtie.py", line 40, in __init__
    self.bowtie_to_unique()
  File "unify_bowtie.py", line 105, in bowtie_to_unique
    chrom = all_chrs[self.ind_chr]
IndexError: list index out of range
done for the 2
```

**Comment by mehrankr** [comment]
I think I know what's going on. Sorry the repo is not tested with -job_id before that's why this is happening.

Can you try this:

```
for i in {1..2}
do
   exort SGE_TASK_ID=$i
    python unify_bowtie.py data/TestGenomeMappability/kmers/k8 data/TestGenomeMappability/chrsize.tsv -var_id SGE_TASK_ID
    echo "done for the $i"
done
```

**Comment by Pooran-Dewari** [comment]
Thanks. Apparently, it does the job without error but the output files are empty.
```
$ . jobs2.sh 
Done with data/TestGenomeMappability/kmers/k8/chr1.0.8.bowtie.gz
For data/TestGenomeMappability/kmers/k8/chr1.k8.uint8.unique.gz found 9 unique regions
Saved data/TestGenomeMappability/kmers/k8/chr1.k8.uint8.unique.gz
Exiting successfully
done for the 1
Done with data/TestGenomeMappability/kmers/k8/chr2.1.8.bowtie.gz
For data/TestGenomeMappability/kmers/k8/chr2.k8.uint8.unique.gz found 5 unique regions
Saved data/TestGenomeMappability/kmers/k8/chr2.k8.uint8.unique.gz
Exiting successfully
done for the 2
```

used this python script from you to read contents (also, can't see illegible outputs using `zcat` as we generally see for binary files)
```
import numpy as np
import gzip

uint_path = "chr1.k8.uint8.unique.gz"
kmer_link = gzip.open(uint_path, "rb")
kmer_ar = np.frombuffer(kmer_link.read(), dtype=np.uint8)
kmer_link.close()
```

**Comment by mehrankr** [comment]
Try this:

```
uint_path = "chr3.k150.uint8.unique.gz"
kmer_link = gzip.open(uint_path, "rb")
kmer_ar = np.frombuffer(kmer_link.read(), dtype=np.uint8)
kmer_link.close()
idx_nonzeros = np.where(kmer_ar > 0)[0]
print("This array has length {} and {} non-unique kmers".format(kmer_ar.shape, len(idx_nonzeros)))
```

**Comment by Pooran-Dewari** [comment]
Many thanks, looks like it says they have something in it. I will use these for Blacklist and see how it goes.
```
$ python open_gz1.py 
This array has length (60,) and 9 non-unique kmers
This array has length (90,) and 5 non-unique kmers

```

**Comment by Pooran-Dewari** [comment]
Hmm my uint gz files look fine by the looks of this command
```
$ python2.7 open_gz.py 
This array chr3.k150.uint8.unique.gz has length (105780080,) and 92901015 non-unique kmers
This array chr6.k150.uint8.unique.gz has length (96060288,) and 83237934 non-unique kmers
```
But when I try `Blacklist`, it can't recognize them.
```
$ Blacklist chr3
Unable to read mappability files!
```
Really not sure what to do now.
But thanks for your help, I really appreciate all your time & support troubleshooting this.

**Comment by mehrankr** [comment]
chr3.k150.uint8.unique.gz is the output of `unify_bowtie` and has 0 and 1 values, where 1 indicates a 150-mer starting at that position is uniquely mappable.

I think `Blacklist` requires the output of `combine_umaps` 
These files will have values corresponding to the k-mers you used for running the study.

For example, if you used k24 and k150, your combine_umap output files will have 3 values; 0, 24, and 150, where 24 means the position is uniquely mappable with any k-mer larger than 24, and 150 means the region is uniquely mappable with any k-mer larger than 150.

**Comment by Pooran-Dewari** [comment]
Thanks for your reply. I will create mappability files for different kmers and use `combine_umaps` output for `Blacklist`.

**Comment by Pooran-Dewari** [comment]
#### umap with kmer 100 and 150
I have the `combine_umaps` for kmer 100 150  ; I did it for chr29 as that's the smallest chromosome, so quicker.
Thanks to you, umap analysis was smooth and below is the output of the combined uint file after `combine_umap` 
```
$ od -t x1 mappability/chr29.uint8.unique | head
0000000 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
*
0000140 00 00 00 00 00 00 00 96 96 96 96 96 96 96 96 96
0000160 96 96 96 96 96 96 96 96 96 96 96 96 96 96 96 96
*
0000220 96 96 96 96 96 96 96 96 96 64 64 64 64 64 64 64
0000240 64 64 64 64 64 64 64 64 64 64 64 64 64 64 64 64
*
0000740 64 64 00 00 00 00 00 00 00 00 00 00 00 00 00 00
0000760 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00

```
#### Blacklist 
Now the Blacklist doesn't complain about the files, it does spit out entire chromosome as high signal though.
```
$ Blacklist chr29
chr29   0       43051100        High Signal Region
```
I am assuming it's because of low number of input files (I used 5 inputs) for the `Blacklist `analysis. I will post on blacklist git issue & hopefully someone from Boyle lab will help me with this. 
Thanks again for your help with umap troubleshooting, much appreciate your time & useful suggestions.
