### ISSUE TITLE
 Zebra fish danRer10 genome mappability data missing

### ISSUE THREAD

**Issue by malcook** [hoffmangroup/umap#2]
https://bismap.hoffmanlab.org/ has a link named "Zebra fish danRer10 genome mappability" which is 404.
Any source of pre-computes for danRer10 would be much appreciated.
Possible?

**Comment by mehrankr** [comment]
This is now available under bismap.hoffmablab.org

**Comment by malcook** [comment]
thanks - of course you mean bismap.hoffmaNlab.org - ;)
