### ISSUE TITLE
request GRCm39 (mm39 ) k100.bismap.bedgraph.gz

### ISSUE THREAD

**Issue by brainfo** [hoffmangroup/umap#6]
Hi, your tool is so helpful! With the new references coming, could you add support to mm39 too?

With appreciation!

**Comment by mehrankr** [comment]
Hello,

bigWig files are now available here: https://bismap.hoffmanlab.org/raw/mm39/umap
Please use UCSC bigWigToBedGraph to convert to bedGraph.

Best,
Mehran
