### ISSUE TITLE
Request for T2T-CHM13 

### ISSUE THREAD

**Issue by The-Hungry-Caterpillar** [hoffmangroup/umap#7]
Hello, 

Is there any chance of you all generating uint8 mappability files for the new gapless [T2T-CHM13](https://github.com/marbl/CHM13) reference genome sometime soon?

Also, thanks so much for the resource!

Best,
Jonathan

**Comment by mehrankr** [comment]
Hello,

This is now available under bismap.hoffmanlab.org

Best,
Mehran

**Comment by bweasels** [comment]
Apologies, but I can't seem to find the T2T uint8 mappability files on bismap.hoffmanlab.org - am I looking in the wrong place?

**Comment by EricR86** [comment]
@bweasels we would recommend using UCSC as a reference for mappability datasets for the time being.

Here is the link for T2T mappability files:
https://hgdownload.soe.ucsc.edu/gbdb/hs1/hoffmanMappability/

There is a better solution with hopefully more useful datasets in the pipeline at the moment but no ETA in the meantime.

**Comment by bweasels** [comment]
great - thanks for replying so quickly!
