### ISSUE TITLE
Regarding virtual environments

### ISSUE THREAD

**Issue by The-Hungry-Caterpillar** [hoffmangroup/umap#8]
Hello,

I need to activate an environment to run python 2.7, e.g. `source /vcu_gpfs2/home/ogataj/src/umap_python/bin/activate`.

However I'm not sure the best way to achieve this... should I run 
`python ubismap.py <options> -write_script fun_run.sh` 
and then edit the subsequent `fun_run.sh` script?

Hoping for help.

Thank you in advance.

**Comment by mehrankr** [comment]
Hello,

I assume you mean you want your individual jobs within the array to run `source <environment>` right?
That's exactly what I had to do on a slurm environment.
If so, you can look into the examples that I have put under the slurm documentation here and in our README:


```
KMERS=(24 36 50 100 150 200)
for kmer in ${KMERS[@]}
do
    JOBNAME=GetKmer.$kmer.Align2
    echo -e '#!/bin/sh' > Scripts/$JOBNAME.sh
    # activating a specific environment 
    echo "source activate py27" >> Scripts/$JOBNAME.sh
    echo "python $PWD/get_kmers.py $MAINDIR/chrsize.tsv $MAINDIR/kmers/k$kmer $MAINDIR/chrs $MAINDIR/chrsize_index.tsv  --var_id SLURM_ARRAY_TASK_ID --kmer k$kmer" >> Scripts/$JOBNAME.sh
    "python run_bowtie.py $MAINDIR/kmers/k$kmer /mnt/work1/software/bowtie/1.1.0 $MAINDIR/genome Umap_bowtie.ind -var_id SLURM_ARRAY_TASK_ID" >> Scripts/$JOBNAME.sh
    sbatch -c 1 -p hoffmangroup --mem=8G -t 12:00:00 --array=1-598%60 -o $MAINDIR/kmers/Bismap.UniqueKmers.Align.LOG -e $MAINDIR/kmers/Bismap.UniqueKmers.Align.ERR Scripts/$JOBNAME.sh
done
```

**Comment by The-Hungry-Caterpillar** [comment]
Okay I see what you mean. You wrapped the python call into a shell script. 
And then for SGE just replace the sbatch line with SGE equivalent arguments (e.g. the output of ubismap.py)


(also should line 9 in your code chunk start with echo?)

Thanks for the quick response!

**Comment by mehrankr** [comment]
Oh yeah absolutely thanks for catching that
